#!/usr/bin/env bash
set -e

echo "[start]: dotfiles"

script_dir=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)
dry="0"

while [[ $# > 0 ]]; do
    echo "ARG: \"$1\""
    if [[ "$1" == "--dry" ]]; then
        dry="1"
    fi
    shift
done

log() {
    if [[ $dry == "1" ]]; then
        echo "[dry]: $@"
    else
        echo "$@"
    fi
}

execute() {
    if [[ $dry == "1" ]]; then
      log "[dry]: $@"
      return
    fi
    log "✅: $@"
    "$@"
}

copy_dir() {
    from=$1
    to=$2

    execute mkdir -p $to

    pushd $from > /dev/null
    dirs=$(find . -mindepth 1 -maxdepth 1 -type d)
    for dir in $dirs; do
      execute rm -rf $to/$dir
      execute cp -r $dir $to/$dir
    done
    popd > /dev/null
}

copy_file() {
    from=$1
    to=$2
    name=$(basename $from)

    execute rm $to/$name
    execute cp $from $to/$name
}

confighome=".test-config"

copy_dir $confighome $HOME/$confighome
copy_file .specialconfig $HOME


echo "[end]: dotfiles"
