#!/usr/bin/env bash
set -e

echo "[start]: $(basename "$0")"

script_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
dry="0"

while [[ $# > 0 ]]; do
    echo "ARG: \"$1\""
    if [[ "$1" == "--dry" ]]; then
        dry="1"
    fi
    shift
done

log() {
    if [[ $dry == "1" ]]; then
        echo "[dry]: $@"
    else
        echo "$@"
    fi
}

execute() {
    if [[ $dry == "1" ]]; then
      log "[dry]: $@"
      return
    fi
    log "✅: $@"
    "$@"
}

copy_dir() {
    from="$1"
    to="$2"

    execute mkdir -p "$to"

    pushd "$from" > /dev/null
    dirs=$(find . -mindepth 1 -maxdepth 1 -type d)
    for dir in $dirs; do
      execute rm -rf "$to/$dir"
      execute cp -r "$dir" "$to/$dir"
    done
    popd > /dev/null
}

copy_file() {
    from="$1"
    to="$2"

    if [ -d "$to" ]; then
        name=$(basename "$from")
        execute rm "$to/$name"
        execute cp "$from" "$to/$name"
    else
        if [ -f "$to" ]; then
            execute rm "$to"
        fi
        execute cp "$from" "$to"
    fi
}

copy_dir "./Library/Application Support/" "$HOME/Library/Application Support"

copy_dir "config" "$HOME/.config"

# dots
copy_file "./dots/dot-gitconfig" "$HOME/.gitconfig"
copy_file "./dots/dot-gitignore" "$HOME/.gitignore"
copy_file "./dots/dot-ideavimrc" "$HOME/.ideavimrc"
copy_file "./dots/dot-iex.exs" "$HOME/.iex.exs"
copy_file "./dots/dot-irbrc" "$HOME/.irbrc"
copy_file "./dots/dot-psqlrc" "$HOME/.psqlrc"
copy_file "./dots/dot-zshrc" "$HOME/.zshrc"
copy_file "./dots/dot-default_gems" "$HOME/.default_gems"
copy_file "./dots/dot-ready-tmux" "$HOME/.ready-tmux"


# can also do this if you don't need to rename the file:
# copy_file ".specialconfig" "$HOME"


echo "[end]: $(basename "$0")"
