#!/usr/bin/env bash

# script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
script_dir=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)

# if [ -z "$DEV_ENV" ]; then
#     echo "env var DEV_ENV needs to be present"
#     exit 1
# fi
#
# # if i just did DEV_ENV=$(pwd) ./run then this is needed for the rest of the
# # scripts
# export DEV_ENV="$DEV_ENV"

grep=""
dry_run="0"

while [[ $# -gt 0 ]]; do
    echo "ARG: \"$1\""
    if [[ "$1" == "--dry" ]]; then
        dry_run="1"
    else
        grep="$1"
    fi
    shift
done

log() {
    if [[ $dry_run == "1" ]]; then
        echo "[DRY_RUN]: $1"
    else
        echo "$1"
    fi
}

log "RUN: env: $env -- grep: $grep"

# runs_dir=`find $script_dir/runs -mindepth 1 -maxdepth 1 -executable`
cd $script_dir
# runs_dir=`find $script_dir/runs -mindepth 1 -maxdepth 1 -type f -exec test -x {} \; -print`
scripts=$(find ./runs -mindepth 1 -maxdepth 1 -type f -exec test -x {} \; -print)

for script in $scripts; do
    if echo "$script" | grep -vq "$grep"; then
        log "grep \"$grep\" filtered out $script"
        continue
    fi

    log "running script: $script"

    if [[ $dry_run == "0" ]]; then
        $script
    fi
done
