#!/usr/bin/env bash

# script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
script_dir=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)
filter=""
dry="0"

while [[ $# > 0 ]]; do
    echo "ARG: \"$1\""
    if [[ "$1" == "--dry" ]]; then
        dry="1"
    else
        filter="$1"
    fi
    shift
done

log() {
    if [[ $dry == "1" ]]; then
        echo "[dry]: $@"
    else
        echo "$@"
    fi
}

execute() {
    if [[ $dry == "1" ]]; then
      log "[dry]: $@"
      return
    fi
    log "✅: $@"
    "$@"
}

log "$script_dir -- $filter"

# runs_dir=`find $script_dir/runs -mindepth 1 -maxdepth 1 -executable`
cd $script_dir
# runs_dir=`find $script_dir/runs -mindepth 1 -maxdepth 1 -type f -exec test -x {} \; -print`
scripts=$(find ./runs -mindepth 1 -maxdepth 1 -type f -exec test -x {} \; -print)

for script in $scripts; do
    if echo "$script" | grep -vq "$filter"; then
        log "❌: $script"
        continue
    fi

    execute ./$script
done
