#!/usr/bin/env bash
set -e

echo "[start]: $(basename "$0")"

# used by Fork for commandline integrations
pushd "/usr/local"
[ ! -d /usr/local/bin ] && sudo mkdir -p /usr/local/bin
popd

echo "[end]: $(basename "$0")"
