#!/usr/bin/env bash
set -e

echo "[start]: $(basename "$0")"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
RUNS_DIR="$(dirname "$SCRIPT_DIR")"

"$RUNS_DIR/install_homebrew"
"$RUNS_DIR/homebrew"
"$RUNS_DIR/zsh"
"$RUNS_DIR/asdf_plugins"
"$RUNS_DIR/neovim"
"$RUNS_DIR/cleanup"

echo "[end]: $(basename "$0")"
