#!/usr/bin/env bash
set -e

echo "[start]: $(basename "$0")"

brew install 1password-cli 
brew install autoconf 
brew install autojump 
brew install automake 
brew install bat 
brew install btop
brew install coreutils 
brew install docker
brew install eza 
brew install fd 
brew install fop 
brew install fzf 
# /opt/homebrew/opt/fzf/install
if [ -f "$HOME/.fzf.zsh" ]; then
  echo "fzf already installed"
else
  $(brew --prefix)/opt/fzf/install
fi
brew install gawk 
brew install git
brew install git-delta 
brew install gpg 
brew install httpie 
brew install lazygit 
brew install libpq 
brew install libtool 
brew install libxslt 
brew install libyaml 
brew install openssl@3 
brew install pngpaste 
brew install readline 
brew install ripgrep 
brew install tmux
brew install tmux 
brew install tree 
brew install vlc 
brew install wget 
brew install wxwidgets

brew install --cask 1password 
brew install --cask keycastr
brew install --cask stats

# brew install --cask font-jetbrains-mono-nerd-font
# brew install --cask font-hack-nerd-font

brew cleanup

echo "[end]: $(basename "$0")"
