#!/usr/bin/env bash
set -e

echo "[start]: $(basename "$0")"
if ! command -v brew &> /dev/null
then
    echo "Homebrew is not installed. Installing now..."
    # Install Homebrew
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    eval "$(/opt/homebrew/bin/brew shellenv)"
else
    echo "Homebrew is already installed."
fi

echo "[end]: $(basename "$0")"

