gui:
  authorColors:
    'jkahne': '#ffff00'
    '*': 'red'
  theme:
    selectedLineBgColor:
      - reverse
  showRandomTip: false
  nerdFontsVersion: "3"
git:
  merging:
    args: '--no-ff'
  autoFetch: false
keybinding:
  universal:
    # quit: <esc>
    scrollUpMain: <c-k>
    scrollDownMain: <c-j>
    commits:
      moveDownCommit: <c-1>
      moveUpCommit: <c-2>
